stages:
  get_imputation_config:
    cmd: python3 scripts/get_imputation_config.py --train_data processed_data/full_train_data.csv   --config_output artifacts/imputation_config.json
    deps:
      - processed_data/full_train_data.csv   
      - scripts/get_imputation_config.py
    outs:
      - artifacts/imputation_config.json
  
  impute_data:
    cmd: python3 scripts/impute_data.py --data processed_data/full_train_data.csv    --imput_config artifacts/imputation_config.json --output processed_data/full_train_data_imp.csv
    deps:
      - processed_data/full_train_data.csv
      - artifacts/imputation_config.json
      - scripts/impute_data.py
    outs:
      - processed_data/full_train_data_imp.csv
  
  get_handcraft_features:
    cmd: python3 scripts/build_handcraft_features.py --input_path processed_data/full_train_data_imp.csv --output_path features_crafted/handcrafted_features.csv
    deps:
      - processed_data/full_train_data_imp.csv
      - scripts/build_handcraft_features.py
    outs:
      - features_crafted/handcrafted_features.csv


  
      


  
    
